package librarymanagementsystem;

public class About extends javax.swing.JFrame {

    String user;
    /**
     * Creates new form About
     */
    public About() {
        initComponents();
    }
    public About(String user){
        this.user = user;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutUsPanel = new javax.swing.JPanel();
        madeByLabel = new javax.swing.JLabel();
        libraryManagementSystemLabel = new javax.swing.JLabel();
        namitaPoddarLabel = new javax.swing.JLabel();
        shivamTripathiLabel = new javax.swing.JLabel();
        libraryImageLabel = new javax.swing.JLabel();
        backToHomeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("About Us");

        aboutUsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        madeByLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        madeByLabel.setText("Made By:");

        libraryManagementSystemLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        libraryManagementSystemLabel.setText("LIBRARY MANAGEMENT SYSTEM");

        namitaPoddarLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        namitaPoddarLabel.setText("Namita Poddar - 72");

        shivamTripathiLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        shivamTripathiLabel.setText("Shivam Tripathi - 106");

        libraryImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/library.png"))); // NOI18N

        backToHomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        backToHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToHomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutUsPanelLayout = new javax.swing.GroupLayout(aboutUsPanel);
        aboutUsPanel.setLayout(aboutUsPanelLayout);
        aboutUsPanelLayout.setHorizontalGroup(
            aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutUsPanelLayout.createSequentialGroup()
                        .addComponent(libraryImageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(libraryManagementSystemLabel))
                    .addComponent(madeByLabel)
                    .addGroup(aboutUsPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aboutUsPanelLayout.createSequentialGroup()
                                .addComponent(shivamTripathiLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                                .addComponent(backToHomeButton))
                            .addComponent(namitaPoddarLabel))))
                .addContainerGap())
        );
        aboutUsPanelLayout.setVerticalGroup(
            aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsPanelLayout.createSequentialGroup()
                .addGroup(aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutUsPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(libraryManagementSystemLabel))
                    .addGroup(aboutUsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(libraryImageLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(madeByLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namitaPoddarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shivamTripathiLabel)
                .addGap(4, 4, 4)
                .addComponent(backToHomeButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutUsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutUsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHomeButtonActionPerformed
        if("admin".equals(user)){
            setVisible(false);
            AdminHome ob = new AdminHome();
            ob.setVisible(true);
        } else{
            setVisible(false);
            Home ob = new Home();
            ob.setVisible(true);
        }
    }//GEN-LAST:event_backToHomeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutUsPanel;
    private javax.swing.JButton backToHomeButton;
    private javax.swing.JLabel libraryImageLabel;
    private javax.swing.JLabel libraryManagementSystemLabel;
    private javax.swing.JLabel madeByLabel;
    private javax.swing.JLabel namitaPoddarLabel;
    private javax.swing.JLabel shivamTripathiLabel;
    // End of variables declaration//GEN-END:variables
}
