package librarymanagementsystem;

public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminOperationPanel = new javax.swing.JPanel();
        viewLibrariansButton = new javax.swing.JButton();
        deleteLibrarianButton = new javax.swing.JButton();
        viewLibrariansLabel = new javax.swing.JLabel();
        deleteLibrarianLabel = new javax.swing.JLabel();
        logoImageLabel = new javax.swing.JLabel();
        navigationMenuBar = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contactUsMenuItem = new javax.swing.JMenuItem();
        aboutUsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Home");

        adminOperationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Operation", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 24))); // NOI18N

        viewLibrariansButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        viewLibrariansButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewLibrarian.png"))); // NOI18N
        viewLibrariansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLibrariansButtonActionPerformed(evt);
            }
        });

        deleteLibrarianButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        deleteLibrarianButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteLibrarian.png"))); // NOI18N
        deleteLibrarianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLibrarianButtonActionPerformed(evt);
            }
        });

        viewLibrariansLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        viewLibrariansLabel.setText("View Librarians ");

        deleteLibrarianLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        deleteLibrarianLabel.setText("Delete Librarian");

        javax.swing.GroupLayout adminOperationPanelLayout = new javax.swing.GroupLayout(adminOperationPanel);
        adminOperationPanel.setLayout(adminOperationPanelLayout);
        adminOperationPanelLayout.setHorizontalGroup(
            adminOperationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminOperationPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(viewLibrariansButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteLibrarianButton)
                .addGap(118, 118, 118))
            .addGroup(adminOperationPanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(viewLibrariansLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteLibrarianLabel)
                .addGap(137, 137, 137))
        );
        adminOperationPanelLayout.setVerticalGroup(
            adminOperationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminOperationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminOperationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewLibrariansButton)
                    .addComponent(deleteLibrarianButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(adminOperationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewLibrariansLabel)
                    .addComponent(deleteLibrarianLabel))
                .addContainerGap())
        );

        logoImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N

        homeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        homeMenu.setText("Home");

        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        homeMenu.add(exitMenuItem);

        logoutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        homeMenu.add(logoutMenuItem);

        navigationMenuBar.add(homeMenu);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        helpMenu.setText("Help");

        contactUsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contactUs.png"))); // NOI18N
        contactUsMenuItem.setText("Contact Us");
        contactUsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactUsMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contactUsMenuItem);

        aboutUsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aboutUs.png"))); // NOI18N
        aboutUsMenuItem.setText("About Us");
        aboutUsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutUsMenuItem);

        navigationMenuBar.add(helpMenu);

        setJMenuBar(navigationMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminOperationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoImageLabel)
                .addGap(18, 18, 18)
                .addComponent(adminOperationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        setVisible(false);
        MainLogin ob = new MainLogin();
        ob.setVisible(true);
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void contactUsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactUsMenuItemActionPerformed
        setVisible(false);
        Contact ob = new Contact("admin");
        ob.setVisible(true);
    }//GEN-LAST:event_contactUsMenuItemActionPerformed

    private void aboutUsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsMenuItemActionPerformed
        setVisible(false);
        About ob = new About("admin");
        ob.setVisible(true);
    }//GEN-LAST:event_aboutUsMenuItemActionPerformed

    private void viewLibrariansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLibrariansButtonActionPerformed
        setVisible(false);
        ViewLibrarian ob = new ViewLibrarian();
        ob.setVisible(true);
    }//GEN-LAST:event_viewLibrariansButtonActionPerformed

    private void deleteLibrarianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLibrarianButtonActionPerformed
        setVisible(false);
        DeleteLibrarian ob = new DeleteLibrarian();
        ob.setVisible(true);
    }//GEN-LAST:event_deleteLibrarianButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutUsMenuItem;
    private javax.swing.JPanel adminOperationPanel;
    private javax.swing.JMenuItem contactUsMenuItem;
    private javax.swing.JButton deleteLibrarianButton;
    private javax.swing.JLabel deleteLibrarianLabel;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JLabel logoImageLabel;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuBar navigationMenuBar;
    private javax.swing.JButton viewLibrariansButton;
    private javax.swing.JLabel viewLibrariansLabel;
    // End of variables declaration//GEN-END:variables
}
