package librarymanagementsystem;

public class Contact extends javax.swing.JFrame {
    
    String user;
    /**
     * Creates new form Contact
     */
    public Contact() {
        initComponents();
    }
    
    public Contact(String user) {
        initComponents();
        this.user = user;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contactUsPanel = new javax.swing.JPanel();
        libraryManagementSystemLabel = new javax.swing.JLabel();
        namitaEmailLabel = new javax.swing.JLabel();
        shivamEmailLabel = new javax.swing.JLabel();
        libraryImageLabel = new javax.swing.JLabel();
        backToAdminHomeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contact Us");

        contactUsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        libraryManagementSystemLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        libraryManagementSystemLabel.setText("LIBRARY MANAGEMENT SYSTEM");

        namitaEmailLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        namitaEmailLabel.setText("Namita Poddar - poddarnamita.13@gmail.com");

        shivamEmailLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        shivamEmailLabel.setText("Shivam Tripathi - tripathishivam11@gmail.com");

        libraryImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/library.png"))); // NOI18N

        backToAdminHomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        backToAdminHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToAdminHomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contactUsPanelLayout = new javax.swing.GroupLayout(contactUsPanel);
        contactUsPanel.setLayout(contactUsPanelLayout);
        contactUsPanelLayout.setHorizontalGroup(
            contactUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactUsPanelLayout.createSequentialGroup()
                .addGroup(contactUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactUsPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backToAdminHomeButton))
                    .addGroup(contactUsPanelLayout.createSequentialGroup()
                        .addGroup(contactUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contactUsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(libraryImageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(libraryManagementSystemLabel))
                            .addGroup(contactUsPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(namitaEmailLabel))
                            .addGroup(contactUsPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(shivamEmailLabel)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contactUsPanelLayout.setVerticalGroup(
            contactUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactUsPanelLayout.createSequentialGroup()
                .addGroup(contactUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contactUsPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(libraryManagementSystemLabel))
                    .addGroup(contactUsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(libraryImageLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(namitaEmailLabel)
                .addGap(18, 18, 18)
                .addComponent(shivamEmailLabel)
                .addGap(30, 30, 30)
                .addComponent(backToAdminHomeButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contactUsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contactUsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToAdminHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToAdminHomeButtonActionPerformed
        if("admin".equals(user)){
            setVisible(false);
            AdminHome ob = new AdminHome();
            ob.setVisible(true);
        } else {
            setVisible(false);
            Home ob = new Home();
            ob.setVisible(true);
        }
    }//GEN-LAST:event_backToAdminHomeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToAdminHomeButton;
    private javax.swing.JPanel contactUsPanel;
    private javax.swing.JLabel libraryImageLabel;
    private javax.swing.JLabel libraryManagementSystemLabel;
    private javax.swing.JLabel namitaEmailLabel;
    private javax.swing.JLabel shivamEmailLabel;
    // End of variables declaration//GEN-END:variables
}
