package librarymanagementsystem;

import java.sql.*;
import javax.swing.JOptionPane;

public class ForgotPassword extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public ForgotPassword() {
        initComponents();
        con = JavaConnect.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forgotPasswordPanel = new javax.swing.JPanel();
        retrivePasswordButton = new javax.swing.JButton();
        librarianUsernameTextField = new javax.swing.JTextField();
        securityQuestionTextField = new javax.swing.JTextField();
        librarianPasswordTextField = new javax.swing.JTextField();
        librarianNameLabel = new javax.swing.JLabel();
        librarianNameTextField = new javax.swing.JTextField();
        librarianUsernameLabel = new javax.swing.JLabel();
        answerTextField = new javax.swing.JTextField();
        librarianPasswordLabel = new javax.swing.JLabel();
        backToLibrarianLoginButton = new javax.swing.JButton();
        answerLabel = new javax.swing.JLabel();
        securityQuestionLabel = new javax.swing.JLabel();
        searchLibrarianButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forgot Password");
        setAutoRequestFocus(false);

        forgotPasswordPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Forgot Password", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 24), new java.awt.Color(255, 0, 0))); // NOI18N

        retrivePasswordButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        retrivePasswordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/retriveDatabase.png"))); // NOI18N
        retrivePasswordButton.setText("Retrive");
        retrivePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrivePasswordButtonActionPerformed(evt);
            }
        });

        librarianUsernameTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        securityQuestionTextField.setEditable(false);
        securityQuestionTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        librarianPasswordTextField.setEditable(false);
        librarianPasswordTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        librarianNameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        librarianNameLabel.setText("Name");

        librarianNameTextField.setEditable(false);
        librarianNameTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        librarianUsernameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        librarianUsernameLabel.setText("Username");

        answerTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        librarianPasswordLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        librarianPasswordLabel.setText("Password");

        backToLibrarianLoginButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        backToLibrarianLoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        backToLibrarianLoginButton.setText("Back");
        backToLibrarianLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLibrarianLoginButtonActionPerformed(evt);
            }
        });

        answerLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        answerLabel.setText("Answer");

        securityQuestionLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        securityQuestionLabel.setText("Your Security Question");

        searchLibrarianButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchLibrarianButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        searchLibrarianButton.setText("Search");
        searchLibrarianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchLibrarianButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forgotPasswordPanelLayout = new javax.swing.GroupLayout(forgotPasswordPanel);
        forgotPasswordPanel.setLayout(forgotPasswordPanelLayout);
        forgotPasswordPanelLayout.setHorizontalGroup(
            forgotPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(forgotPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forgotPasswordPanelLayout.createSequentialGroup()
                        .addComponent(securityQuestionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(securityQuestionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(forgotPasswordPanelLayout.createSequentialGroup()
                        .addGroup(forgotPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(librarianUsernameLabel)
                            .addComponent(librarianNameLabel))
                        .addGap(103, 103, 103)
                        .addGroup(forgotPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(librarianUsernameTextField)
                            .addComponent(librarianNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(searchLibrarianButton))
                    .addGroup(forgotPasswordPanelLayout.createSequentialGroup()
                        .addGroup(forgotPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answerLabel)
                            .addComponent(librarianPasswordLabel))
                        .addGap(108, 108, 108)
                        .addGroup(forgotPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(answerTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(librarianPasswordTextField))
                        .addGap(18, 18, 18)
                        .addGroup(forgotPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retrivePasswordButton)
                            .addComponent(backToLibrarianLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        forgotPasswordPanelLayout.setVerticalGroup(
            forgotPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(forgotPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forgotPasswordPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(librarianNameLabel))
                    .addGroup(forgotPasswordPanelLayout.createSequentialGroup()
                        .addGroup(forgotPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(librarianUsernameLabel)
                            .addComponent(librarianUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchLibrarianButton))
                        .addGap(18, 18, 18)
                        .addComponent(librarianNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(forgotPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(securityQuestionLabel)
                    .addComponent(securityQuestionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(forgotPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forgotPasswordPanelLayout.createSequentialGroup()
                        .addGroup(forgotPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(answerLabel)
                            .addComponent(answerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(forgotPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(librarianPasswordLabel)
                            .addComponent(librarianPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backToLibrarianLoginButton)))
                    .addComponent(retrivePasswordButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forgotPasswordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forgotPasswordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchLibrarianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchLibrarianButtonActionPerformed
        try {
            pst = con.prepareStatement("Select * from librarian where username =?"); 
            pst.setString(1, librarianUsernameTextField.getText());
            rs = pst.executeQuery();
           
            if(rs.next()) {
                librarianNameTextField.setText(rs.getString(2));
                securityQuestionTextField.setText(rs.getString(5));
                rs.close();
                pst.close();    
            }
            else {
                JOptionPane.showMessageDialog(null, "Incorrect Username");
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchLibrarianButtonActionPerformed

    private void retrivePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrivePasswordButtonActionPerformed
        try {
            pst = con.prepareStatement("Select * from librarian where answer = ? && username = ?"); 
            pst.setString(1, answerTextField.getText());
            pst.setString(2, librarianUsernameTextField.getText());
            rs = pst.executeQuery();
           
            if(rs.next()){
                librarianPasswordTextField.setText(rs.getString(4));
                rs.close();
                pst.close();    
            }
            else{
                JOptionPane.showMessageDialog(null, "Incorrect Answer");
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_retrivePasswordButtonActionPerformed

    private void backToLibrarianLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLibrarianLoginButtonActionPerformed
        setVisible(false);
        LibrarianLogin ob = new LibrarianLogin();
        ob.setVisible(true);
    }//GEN-LAST:event_backToLibrarianLoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerLabel;
    private javax.swing.JTextField answerTextField;
    private javax.swing.JButton backToLibrarianLoginButton;
    private javax.swing.JPanel forgotPasswordPanel;
    private javax.swing.JLabel librarianNameLabel;
    private javax.swing.JTextField librarianNameTextField;
    private javax.swing.JLabel librarianPasswordLabel;
    private javax.swing.JTextField librarianPasswordTextField;
    private javax.swing.JLabel librarianUsernameLabel;
    private javax.swing.JTextField librarianUsernameTextField;
    private javax.swing.JButton retrivePasswordButton;
    private javax.swing.JButton searchLibrarianButton;
    private javax.swing.JLabel securityQuestionLabel;
    private javax.swing.JTextField securityQuestionTextField;
    // End of variables declaration//GEN-END:variables
}
