package librarymanagementsystem;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoImageLabel = new javax.swing.JLabel();
        librarianOperationPanel = new javax.swing.JPanel();
        addNewStudentButton = new javax.swing.JButton();
        addNewBookButton = new javax.swing.JButton();
        showStatisticsButton = new javax.swing.JButton();
        addNewBookLabel = new javax.swing.JLabel();
        showStatisticsLabel = new javax.swing.JLabel();
        addNewStudentLabel = new javax.swing.JLabel();
        librarianActionPanel = new javax.swing.JPanel();
        issueBookButton = new javax.swing.JButton();
        aboutUsButton = new javax.swing.JButton();
        issueBookLabel = new javax.swing.JLabel();
        returnBookButton = new javax.swing.JButton();
        returnBookLabel = new javax.swing.JLabel();
        aboutUsLabel = new javax.swing.JLabel();
        navigationMenuBar = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contactUsMenuItem = new javax.swing.JMenuItem();
        aboutUsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        logoImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N

        librarianOperationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Operation", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 24))); // NOI18N

        addNewStudentButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        addNewStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeAddStudent.png"))); // NOI18N
        addNewStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewStudentButtonActionPerformed(evt);
            }
        });

        addNewBookButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        addNewBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeAddBook.png"))); // NOI18N
        addNewBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewBookButtonActionPerformed(evt);
            }
        });

        showStatisticsButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        showStatisticsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeStatistics.png"))); // NOI18N
        showStatisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStatisticsButtonActionPerformed(evt);
            }
        });

        addNewBookLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        addNewBookLabel.setText("New Book ");

        showStatisticsLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        showStatisticsLabel.setText("Statistics");

        addNewStudentLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        addNewStudentLabel.setText("New Student");

        javax.swing.GroupLayout librarianOperationPanelLayout = new javax.swing.GroupLayout(librarianOperationPanel);
        librarianOperationPanel.setLayout(librarianOperationPanelLayout);
        librarianOperationPanelLayout.setHorizontalGroup(
            librarianOperationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, librarianOperationPanelLayout.createSequentialGroup()
                .addGroup(librarianOperationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(librarianOperationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addNewBookButton))
                    .addGroup(librarianOperationPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(addNewBookLabel)))
                .addGroup(librarianOperationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(librarianOperationPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(showStatisticsButton))
                    .addGroup(librarianOperationPanelLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(showStatisticsLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(librarianOperationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addNewStudentButton)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, librarianOperationPanelLayout.createSequentialGroup()
                        .addComponent(addNewStudentLabel)
                        .addGap(26, 26, 26)))
                .addContainerGap())
        );
        librarianOperationPanelLayout.setVerticalGroup(
            librarianOperationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(librarianOperationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(librarianOperationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addNewStudentButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addNewBookButton)
                    .addComponent(showStatisticsButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(librarianOperationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(librarianOperationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(showStatisticsLabel)
                        .addComponent(addNewStudentLabel))
                    .addComponent(addNewBookLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        librarianActionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Action", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 24))); // NOI18N

        issueBookButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        issueBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeIssueBook.png"))); // NOI18N
        issueBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookButtonActionPerformed(evt);
            }
        });

        aboutUsButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        aboutUsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeAbout.png"))); // NOI18N
        aboutUsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsButtonActionPerformed(evt);
            }
        });

        issueBookLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        issueBookLabel.setText("Issue Book");

        returnBookButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        returnBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeReturnBook.png"))); // NOI18N
        returnBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookButtonActionPerformed(evt);
            }
        });

        returnBookLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        returnBookLabel.setText("Return Book");

        aboutUsLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        aboutUsLabel.setText("About");

        javax.swing.GroupLayout librarianActionPanelLayout = new javax.swing.GroupLayout(librarianActionPanel);
        librarianActionPanel.setLayout(librarianActionPanelLayout);
        librarianActionPanelLayout.setHorizontalGroup(
            librarianActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(librarianActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(librarianActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(librarianActionPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(issueBookLabel))
                    .addComponent(issueBookButton))
                .addGroup(librarianActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(librarianActionPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(returnBookButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aboutUsButton)
                        .addContainerGap())
                    .addGroup(librarianActionPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(returnBookLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aboutUsLabel)
                        .addGap(72, 72, 72))))
        );
        librarianActionPanelLayout.setVerticalGroup(
            librarianActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(librarianActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(librarianActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(issueBookButton)
                    .addComponent(aboutUsButton)
                    .addComponent(returnBookButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(librarianActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnBookLabel)
                    .addComponent(aboutUsLabel)
                    .addComponent(issueBookLabel))
                .addContainerGap())
        );

        homeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        homeMenu.setText("Home");

        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        homeMenu.add(exitMenuItem);

        logoutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        homeMenu.add(logoutMenuItem);

        navigationMenuBar.add(homeMenu);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        helpMenu.setText("Help");

        contactUsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contactUs.png"))); // NOI18N
        contactUsMenuItem.setText("Contact Us");
        contactUsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactUsMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contactUsMenuItem);

        aboutUsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aboutUs.png"))); // NOI18N
        aboutUsMenuItem.setText("About Us");
        aboutUsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutUsMenuItem);

        navigationMenuBar.add(helpMenu);

        setJMenuBar(navigationMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(librarianOperationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(librarianActionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoImageLabel)
                .addGap(18, 18, 18)
                .addComponent(librarianOperationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(librarianActionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        setVisible(false);
        MainLogin ob = new MainLogin();
        ob.setVisible(true);
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void addNewBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBookButtonActionPerformed
        setVisible(false);
        NewBook ob = new NewBook();
        ob.setVisible(true);
    }//GEN-LAST:event_addNewBookButtonActionPerformed

    private void addNewStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewStudentButtonActionPerformed
        setVisible(false);
        NewStudent ob = new NewStudent();
        ob.setVisible(true);
    }//GEN-LAST:event_addNewStudentButtonActionPerformed

    private void issueBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookButtonActionPerformed
        setVisible(false);
        IssueBook ob = new IssueBook();
        ob.setVisible(true);
    }//GEN-LAST:event_issueBookButtonActionPerformed

    private void returnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookButtonActionPerformed
        setVisible(false);
        ReturnBook ob = new ReturnBook();
        ob.setVisible(true);
    }//GEN-LAST:event_returnBookButtonActionPerformed

    private void aboutUsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsButtonActionPerformed
        setVisible(false);
        About ob = new About();
        ob.setVisible(true);
    }//GEN-LAST:event_aboutUsButtonActionPerformed

    private void showStatisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStatisticsButtonActionPerformed
        setVisible(false);
        Statistics ob = new Statistics();
        ob.setVisible(true);
    }//GEN-LAST:event_showStatisticsButtonActionPerformed

    private void contactUsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactUsMenuItemActionPerformed
        setVisible(false);
        Contact ob = new Contact();
        ob.setVisible(true);
    }//GEN-LAST:event_contactUsMenuItemActionPerformed

    private void aboutUsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsMenuItemActionPerformed
        setVisible(false);
        About ob = new About();
        ob.setVisible(true);
    }//GEN-LAST:event_aboutUsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutUsButton;
    private javax.swing.JLabel aboutUsLabel;
    private javax.swing.JMenuItem aboutUsMenuItem;
    private javax.swing.JButton addNewBookButton;
    private javax.swing.JLabel addNewBookLabel;
    private javax.swing.JButton addNewStudentButton;
    private javax.swing.JLabel addNewStudentLabel;
    private javax.swing.JMenuItem contactUsMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JButton issueBookButton;
    private javax.swing.JLabel issueBookLabel;
    private javax.swing.JPanel librarianActionPanel;
    private javax.swing.JPanel librarianOperationPanel;
    private javax.swing.JLabel logoImageLabel;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuBar navigationMenuBar;
    private javax.swing.JButton returnBookButton;
    private javax.swing.JLabel returnBookLabel;
    private javax.swing.JButton showStatisticsButton;
    private javax.swing.JLabel showStatisticsLabel;
    // End of variables declaration//GEN-END:variables
}
