package librarymanagementsystem;

import java.sql.*;
import javax.swing.JOptionPane;

public class IssueBook extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst;  
    ResultSet rs;
    
    public IssueBook() {
        initComponents();
        con = JavaConnect.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookAndStudentDetailsPanel = new javax.swing.JPanel();
        bookDetailsPanel = new javax.swing.JPanel();
        bookEditionTextField = new javax.swing.JTextField();
        bookNameTextField = new javax.swing.JTextField();
        bookPriceLabel = new javax.swing.JLabel();
        bookIDTextField = new javax.swing.JTextField();
        bookEditionLabel = new javax.swing.JLabel();
        bookPriceTextField = new javax.swing.JTextField();
        bookPublisherTextField = new javax.swing.JTextField();
        bookIDLabel = new javax.swing.JLabel();
        bookPublisherLabel = new javax.swing.JLabel();
        bookNameLabel = new javax.swing.JLabel();
        bookSearchButton = new javax.swing.JButton();
        dateOfIssueLabel = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        backToHomeButton = new javax.swing.JButton();
        issueBookButton = new javax.swing.JButton();
        studentDetailsPanel = new javax.swing.JPanel();
        studentSemesterTextField = new javax.swing.JTextField();
        studentNameLabel = new javax.swing.JLabel();
        studentCourseTextField = new javax.swing.JTextField();
        studentCourseLabel = new javax.swing.JLabel();
        studentIDTextField = new javax.swing.JTextField();
        studentYearLabel = new javax.swing.JLabel();
        studentNameTextField = new javax.swing.JTextField();
        studentIDLabel = new javax.swing.JLabel();
        studentSemesterLabel = new javax.swing.JLabel();
        studentYearTextField = new javax.swing.JTextField();
        studentSearchButton = new javax.swing.JButton();
        issueBookPanel = new javax.swing.JPanel();
        issueBookLabel = new javax.swing.JLabel();
        issueBookImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Issue Book");

        bookDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Book Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 24))); // NOI18N

        bookEditionTextField.setEditable(false);
        bookEditionTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        bookNameTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        bookPriceLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookPriceLabel.setText("Price");

        bookIDTextField.setEditable(false);
        bookIDTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        bookEditionLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookEditionLabel.setText("Edition");

        bookPriceTextField.setEditable(false);
        bookPriceTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        bookPublisherTextField.setEditable(false);
        bookPublisherTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        bookIDLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookIDLabel.setText("Book ID");

        bookPublisherLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookPublisherLabel.setText("Publisher");

        bookNameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookNameLabel.setText("Book Name");

        bookSearchButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        bookSearchButton.setText("Search");
        bookSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookDetailsPanelLayout = new javax.swing.GroupLayout(bookDetailsPanel);
        bookDetailsPanel.setLayout(bookDetailsPanelLayout);
        bookDetailsPanelLayout.setHorizontalGroup(
            bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookIDLabel)
                    .addComponent(bookEditionLabel)
                    .addComponent(bookPublisherLabel)
                    .addComponent(bookPriceLabel)
                    .addComponent(bookNameLabel))
                .addGap(69, 69, 69)
                .addGroup(bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bookPriceTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(bookPublisherTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookEditionTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookIDTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookNameTextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(bookSearchButton)
                .addContainerGap())
        );
        bookDetailsPanelLayout.setVerticalGroup(
            bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookNameLabel)
                    .addComponent(bookSearchButton))
                .addGap(18, 18, 18)
                .addGroup(bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookIDLabel)
                    .addComponent(bookIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookEditionLabel)
                    .addComponent(bookEditionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookPublisherLabel)
                    .addComponent(bookPublisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookPriceLabel)
                    .addComponent(bookPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dateOfIssueLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dateOfIssueLabel.setText("Date of Issue");

        dateChooserCombo1.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserCombo1.setCalendarPreferredSize(new java.awt.Dimension(300, 200));
    dateChooserCombo1.setFormat(2);
    dateChooserCombo1.setFieldFont(new java.awt.Font("Calibri", java.awt.Font.PLAIN, 18));

    backToHomeButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    backToHomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
    backToHomeButton.setText("Back");
    backToHomeButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            backToHomeButtonActionPerformed(evt);
        }
    });

    issueBookButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    issueBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/issue.png"))); // NOI18N
    issueBookButton.setText("Issue");
    issueBookButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            issueBookButtonActionPerformed(evt);
        }
    });

    studentDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Student Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 24))); // NOI18N

    studentSemesterTextField.setEditable(false);
    studentSemesterTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

    studentNameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    studentNameLabel.setText("Student Name");

    studentCourseTextField.setEditable(false);
    studentCourseTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

    studentCourseLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    studentCourseLabel.setText("Course");

    studentIDTextField.setEditable(false);
    studentIDTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

    studentYearLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    studentYearLabel.setText("Year");

    studentNameTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

    studentIDLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    studentIDLabel.setText("Student ID");

    studentSemesterLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    studentSemesterLabel.setText("Semester");

    studentYearTextField.setEditable(false);
    studentYearTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

    studentSearchButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    studentSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
    studentSearchButton.setText("Search");
    studentSearchButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            studentSearchButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout studentDetailsPanelLayout = new javax.swing.GroupLayout(studentDetailsPanel);
    studentDetailsPanel.setLayout(studentDetailsPanelLayout);
    studentDetailsPanelLayout.setHorizontalGroup(
        studentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(studentDetailsPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(studentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(studentNameLabel)
                .addComponent(studentCourseLabel)
                .addComponent(studentYearLabel)
                .addComponent(studentSemesterLabel)
                .addComponent(studentIDLabel))
            .addGap(69, 69, 69)
            .addGroup(studentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(studentNameTextField)
                .addComponent(studentIDTextField)
                .addComponent(studentCourseTextField)
                .addComponent(studentYearTextField)
                .addComponent(studentSemesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(studentSearchButton)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    studentDetailsPanelLayout.setVerticalGroup(
        studentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(studentDetailsPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(studentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(studentDetailsPanelLayout.createSequentialGroup()
                    .addGroup(studentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentSearchButton)
                        .addComponent(studentNameLabel))
                    .addGap(18, 18, 18)
                    .addGroup(studentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentIDLabel))
                    .addGap(18, 18, 18)
                    .addGroup(studentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentCourseLabel)
                        .addComponent(studentCourseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(studentYearLabel))
                .addComponent(studentYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(studentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(studentSemesterLabel)
                .addComponent(studentSemesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(19, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout bookAndStudentDetailsPanelLayout = new javax.swing.GroupLayout(bookAndStudentDetailsPanel);
    bookAndStudentDetailsPanel.setLayout(bookAndStudentDetailsPanelLayout);
    bookAndStudentDetailsPanelLayout.setHorizontalGroup(
        bookAndStudentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(bookAndStudentDetailsPanelLayout.createSequentialGroup()
            .addGroup(bookAndStudentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bookAndStudentDetailsPanelLayout.createSequentialGroup()
                    .addComponent(bookDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookAndStudentDetailsPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(bookAndStudentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(issueBookButton)
                        .addComponent(dateOfIssueLabel))
                    .addGap(48, 48, 48)))
            .addGroup(bookAndStudentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bookAndStudentDetailsPanelLayout.createSequentialGroup()
                    .addComponent(studentDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(bookAndStudentDetailsPanelLayout.createSequentialGroup()
                    .addGroup(bookAndStudentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(backToHomeButton)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(343, 343, 343))))
    );
    bookAndStudentDetailsPanelLayout.setVerticalGroup(
        bookAndStudentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(bookAndStudentDetailsPanelLayout.createSequentialGroup()
            .addGroup(bookAndStudentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bookDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(studentDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30)
            .addGroup(bookAndStudentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dateOfIssueLabel)
                .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(bookAndStudentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(issueBookButton)
                .addComponent(backToHomeButton))
            .addContainerGap(14, Short.MAX_VALUE))
    );

    issueBookLabel.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
    issueBookLabel.setForeground(new java.awt.Color(51, 0, 204));
    issueBookLabel.setText("Issue Book");

    issueBookImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/issueBook.png"))); // NOI18N

    javax.swing.GroupLayout issueBookPanelLayout = new javax.swing.GroupLayout(issueBookPanel);
    issueBookPanel.setLayout(issueBookPanelLayout);
    issueBookPanelLayout.setHorizontalGroup(
        issueBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(issueBookPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(issueBookImageLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(issueBookLabel)
            .addContainerGap())
    );
    issueBookPanelLayout.setVerticalGroup(
        issueBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(issueBookPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(issueBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(issueBookImageLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, issueBookPanelLayout.createSequentialGroup()
                    .addComponent(issueBookLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(355, 355, 355)
                    .addComponent(issueBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(bookAndStudentDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(issueBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(bookAndStudentDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHomeButtonActionPerformed
        setVisible(false);
        Home ob = new Home();
        ob.setVisible(true);
    }//GEN-LAST:event_backToHomeButtonActionPerformed

    private void bookSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSearchButtonActionPerformed
        try{
            pst = con.prepareStatement("select * from book where book_name = ?");
            pst.setString(1, bookNameTextField.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                bookIDTextField.setText(rs.getString(1));
                bookEditionTextField.setText(rs.getString(3));
                bookPublisherTextField.setText(rs.getString(4));
                bookPriceTextField.setText(rs.getString(5));
                rs.close();
                pst.close();
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Book Name");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_bookSearchButtonActionPerformed

    private void studentSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSearchButtonActionPerformed
        try{
            pst = con.prepareStatement("select * from student where student_name = ?");
            pst.setString(1, studentNameTextField.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                studentIDTextField.setText(rs.getString(1));
                studentCourseTextField.setText(rs.getString(3));
                studentYearTextField.setText(rs.getString(4));
                studentSemesterTextField.setText(rs.getString(5));   
                rs.close();
                pst.close();
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Student Name");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_studentSearchButtonActionPerformed

    private void issueBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookButtonActionPerformed
        try{
            Increment in = new Increment();
            int id = in.IssueBookIncrement();
            pst = con.prepareStatement("insert into issue_book values(?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setInt(1, id);
            pst.setString(2, bookNameTextField.getText());
            pst.setString(3, bookIDTextField.getText());
            pst.setString(4, bookEditionTextField.getText());
            pst.setString(5, bookPublisherTextField.getText());
            pst.setString(6, bookPriceTextField.getText());
            pst.setString(7, studentNameTextField.getText());
            pst.setString(8, studentIDTextField.getText());
            pst.setString(9, studentCourseTextField.getText());
            pst.setString(10, studentYearTextField.getText());
            pst.setString(11, studentSemesterTextField.getText());
            pst.setString(12, (String)dateChooserCombo1.getText());
            int result = pst.executeUpdate();
            if(result ==1){
                JOptionPane.showMessageDialog(null, "Book Issued");
            }
            else{
                JOptionPane.showMessageDialog(null, "Something went wrong...");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_issueBookButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToHomeButton;
    private javax.swing.JPanel bookAndStudentDetailsPanel;
    private javax.swing.JPanel bookDetailsPanel;
    private javax.swing.JLabel bookEditionLabel;
    private javax.swing.JTextField bookEditionTextField;
    private javax.swing.JLabel bookIDLabel;
    private javax.swing.JTextField bookIDTextField;
    private javax.swing.JLabel bookNameLabel;
    private javax.swing.JTextField bookNameTextField;
    private javax.swing.JLabel bookPriceLabel;
    private javax.swing.JTextField bookPriceTextField;
    private javax.swing.JLabel bookPublisherLabel;
    private javax.swing.JTextField bookPublisherTextField;
    private javax.swing.JButton bookSearchButton;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JLabel dateOfIssueLabel;
    private javax.swing.JButton issueBookButton;
    private javax.swing.JLabel issueBookImageLabel;
    private javax.swing.JLabel issueBookLabel;
    private javax.swing.JPanel issueBookPanel;
    private javax.swing.JLabel studentCourseLabel;
    private javax.swing.JTextField studentCourseTextField;
    private javax.swing.JPanel studentDetailsPanel;
    private javax.swing.JLabel studentIDLabel;
    private javax.swing.JTextField studentIDTextField;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JTextField studentNameTextField;
    private javax.swing.JButton studentSearchButton;
    private javax.swing.JLabel studentSemesterLabel;
    private javax.swing.JTextField studentSemesterTextField;
    private javax.swing.JLabel studentYearLabel;
    private javax.swing.JTextField studentYearTextField;
    // End of variables declaration//GEN-END:variables
}
