package librarymanagementsystem;

import java.sql.*;
import javax.swing.JOptionPane;

public class LibrarianLogin extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public LibrarianLogin() {
        initComponents();
        con = JavaConnect.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        librarianLoginPanel = new javax.swing.JPanel();
        librarianUsernameTextField = new javax.swing.JTextField();
        passwordImageLabel = new javax.swing.JLabel();
        librarianUsernameLabel = new javax.swing.JLabel();
        librarianPasswordLabel = new javax.swing.JLabel();
        librarianLoginButton = new javax.swing.JButton();
        forgotPasswordButton = new javax.swing.JButton();
        troubleLoginLabel = new javax.swing.JLabel();
        usernameImageLabel = new javax.swing.JLabel();
        librarianSignUpButton = new javax.swing.JButton();
        backToMainLoginButton = new javax.swing.JButton();
        librarianPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Librarian Login");

        librarianLoginPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Librarian Login", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 24))); // NOI18N

        librarianUsernameTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        passwordImageLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        passwordImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N

        librarianUsernameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        librarianUsernameLabel.setText("Username");

        librarianPasswordLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        librarianPasswordLabel.setText("Password");

        librarianLoginButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        librarianLoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        librarianLoginButton.setText("Login");
        librarianLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianLoginButtonActionPerformed(evt);
            }
        });

        forgotPasswordButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        forgotPasswordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forgotPassword.png"))); // NOI18N
        forgotPasswordButton.setText("Forgot Password");
        forgotPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPasswordButtonActionPerformed(evt);
            }
        });

        troubleLoginLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        troubleLoginLabel.setForeground(new java.awt.Color(255, 0, 0));
        troubleLoginLabel.setText("Trouble Login?");

        usernameImageLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        usernameImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/username.png"))); // NOI18N

        librarianSignUpButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        librarianSignUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signIn.png"))); // NOI18N
        librarianSignUpButton.setText("Sign Up");
        librarianSignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianSignUpButtonActionPerformed(evt);
            }
        });

        backToMainLoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        backToMainLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainLoginButtonActionPerformed(evt);
            }
        });

        librarianPasswordField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        javax.swing.GroupLayout librarianLoginPanelLayout = new javax.swing.GroupLayout(librarianLoginPanel);
        librarianLoginPanel.setLayout(librarianLoginPanelLayout);
        librarianLoginPanelLayout.setHorizontalGroup(
            librarianLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(librarianLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(librarianLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(librarianLoginPanelLayout.createSequentialGroup()
                        .addComponent(troubleLoginLabel)
                        .addGap(16, 16, 16)
                        .addComponent(forgotPasswordButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backToMainLoginButton))
                    .addGroup(librarianLoginPanelLayout.createSequentialGroup()
                        .addGroup(librarianLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(librarianUsernameLabel)
                            .addComponent(librarianPasswordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(librarianLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(librarianLoginPanelLayout.createSequentialGroup()
                                .addComponent(librarianLoginButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(librarianSignUpButton))
                            .addGroup(librarianLoginPanelLayout.createSequentialGroup()
                                .addGroup(librarianLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(librarianUsernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(librarianPasswordField))
                                .addGap(18, 18, 18)
                                .addGroup(librarianLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameImageLabel)
                                    .addComponent(passwordImageLabel))))))
                .addContainerGap())
        );
        librarianLoginPanelLayout.setVerticalGroup(
            librarianLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(librarianLoginPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(librarianLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(librarianLoginPanelLayout.createSequentialGroup()
                        .addComponent(usernameImageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passwordImageLabel))
                    .addGroup(librarianLoginPanelLayout.createSequentialGroup()
                        .addGroup(librarianLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(librarianUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(librarianUsernameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(librarianLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(librarianPasswordLabel)
                            .addComponent(librarianPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(librarianLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(librarianLoginButton)
                    .addComponent(librarianSignUpButton))
                .addGap(18, 18, 18)
                .addGroup(librarianLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(librarianLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(forgotPasswordButton)
                        .addComponent(troubleLoginLabel))
                    .addComponent(backToMainLoginButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(librarianLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(librarianLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToMainLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainLoginButtonActionPerformed
        setVisible(false);
        MainLogin ob = new MainLogin();
        ob.setVisible(true);
    }//GEN-LAST:event_backToMainLoginButtonActionPerformed

    private void librarianSignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianSignUpButtonActionPerformed
        setVisible(false);
        SignUp ob = new SignUp();
        ob.setVisible(true);
    }//GEN-LAST:event_librarianSignUpButtonActionPerformed

    private void forgotPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPasswordButtonActionPerformed
        setVisible(false);
        ForgotPassword ob = new ForgotPassword();
        ob.setVisible(true);
    }//GEN-LAST:event_forgotPasswordButtonActionPerformed

    private void librarianLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianLoginButtonActionPerformed
        try{
            pst = con.prepareStatement("select * from librarian where username = ? && password = ?");   
            pst.setString(1, librarianUsernameTextField.getText());
            pst.setString(2, librarianPasswordField.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                rs.close();
                pst.close();
                
                setVisible(false);
                Home ob = new Home();
                //ob.setUpLoading();
                ob.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Incorrect Username or Password");
            }
          
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_librarianLoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMainLoginButton;
    private javax.swing.JButton forgotPasswordButton;
    private javax.swing.JButton librarianLoginButton;
    private javax.swing.JPanel librarianLoginPanel;
    private javax.swing.JPasswordField librarianPasswordField;
    private javax.swing.JLabel librarianPasswordLabel;
    private javax.swing.JButton librarianSignUpButton;
    private javax.swing.JLabel librarianUsernameLabel;
    private javax.swing.JTextField librarianUsernameTextField;
    private javax.swing.JLabel passwordImageLabel;
    private javax.swing.JLabel troubleLoginLabel;
    private javax.swing.JLabel usernameImageLabel;
    // End of variables declaration//GEN-END:variables
}
