package librarymanagementsystem;

import java.sql.*;
import javax.swing.JOptionPane;

public class NewBook extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst;  
    ResultSet rs;
    
    public NewBook() {
        initComponents();
        con = JavaConnect.ConnecrDb();
        Increment in = new Increment();
        int id = in.BookIncrement();
        bookIDTextField.setText(""+id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newBookPanel = new javax.swing.JPanel();
        bookEditionLabel = new javax.swing.JLabel();
        bookPublisherLabel = new javax.swing.JLabel();
        bookPriceLabel = new javax.swing.JLabel();
        bookPriceTextField = new javax.swing.JTextField();
        bookEditionComboBox = new javax.swing.JComboBox<>();
        bookPublisherTextField = new javax.swing.JTextField();
        bookIDLabel = new javax.swing.JLabel();
        bookIDTextField = new javax.swing.JTextField();
        addBookButton = new javax.swing.JButton();
        backToHomeButton = new javax.swing.JButton();
        bookNameTextField = new javax.swing.JTextField();
        bookNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Book");

        newBookPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "New Book", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 24))); // NOI18N

        bookEditionLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookEditionLabel.setText("Edition");

        bookPublisherLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookPublisherLabel.setText("Publisher");

        bookPriceLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookPriceLabel.setText("Price");

        bookPriceTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        bookEditionComboBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookEditionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        bookPublisherTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        bookIDLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookIDLabel.setText("Book ID");

        bookIDTextField.setEditable(false);
        bookIDTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        addBookButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        addBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addBook.png"))); // NOI18N
        addBookButton.setText("Add");
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        backToHomeButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        backToHomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        backToHomeButton.setText("Back");
        backToHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToHomeButtonActionPerformed(evt);
            }
        });

        bookNameTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        bookNameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookNameLabel.setText("Name");

        javax.swing.GroupLayout newBookPanelLayout = new javax.swing.GroupLayout(newBookPanel);
        newBookPanel.setLayout(newBookPanelLayout);
        newBookPanelLayout.setHorizontalGroup(
            newBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(newBookPanelLayout.createSequentialGroup()
                        .addGroup(newBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookEditionLabel)
                            .addComponent(bookNameLabel)
                            .addComponent(bookIDLabel))
                        .addGap(27, 27, 27)
                        .addGroup(newBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookIDTextField)
                            .addComponent(bookNameTextField)
                            .addComponent(bookEditionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(newBookPanelLayout.createSequentialGroup()
                        .addGroup(newBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookPublisherLabel)
                            .addComponent(bookPriceLabel))
                        .addGap(18, 18, 18)
                        .addGroup(newBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(newBookPanelLayout.createSequentialGroup()
                                .addComponent(addBookButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backToHomeButton))
                            .addComponent(bookPublisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        newBookPanelLayout.setVerticalGroup(
            newBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookIDLabel)
                    .addComponent(bookIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookNameLabel)
                    .addComponent(bookNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookEditionLabel)
                    .addComponent(bookEditionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookPublisherLabel)
                    .addComponent(bookPublisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookPriceLabel)
                    .addComponent(bookPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookButton)
                    .addComponent(backToHomeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHomeButtonActionPerformed
        setVisible(false);
        Home ob = new Home();
        ob.setVisible(true);
    }//GEN-LAST:event_backToHomeButtonActionPerformed

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButtonActionPerformed
        try{
            pst = con.prepareStatement("insert into book values (?,?,?,?,?)");
            pst.setString(1, bookIDTextField.getText());
            pst.setString(2, bookNameTextField.getText());
            pst.setString(3, (String) bookEditionComboBox.getSelectedItem());
            pst.setString(4, bookPublisherTextField.getText());
            pst.setString(5, bookPriceTextField.getText());
            int result = pst.executeUpdate();
            if(result==1){
                JOptionPane.showMessageDialog(null,"New Book Added");     
            }
            else{
                 JOptionPane.showMessageDialog(null,"Failed...");
            }
            //close Connection
            pst.close();
            con.close();;
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_addBookButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookButton;
    private javax.swing.JButton backToHomeButton;
    private javax.swing.JComboBox<String> bookEditionComboBox;
    private javax.swing.JLabel bookEditionLabel;
    private javax.swing.JLabel bookIDLabel;
    private javax.swing.JTextField bookIDTextField;
    private javax.swing.JLabel bookNameLabel;
    private javax.swing.JTextField bookNameTextField;
    private javax.swing.JLabel bookPriceLabel;
    private javax.swing.JTextField bookPriceTextField;
    private javax.swing.JLabel bookPublisherLabel;
    private javax.swing.JTextField bookPublisherTextField;
    private javax.swing.JPanel newBookPanel;
    // End of variables declaration//GEN-END:variables
}
