package librarymanagementsystem;

import java.sql.*;
import javax.swing.JOptionPane;

public class ReturnBook extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;  
    ResultSet rs;
    
    public ReturnBook() {
        initComponents();
        con = JavaConnect.ConnecrDb();
    }
    
    public void Delete(){
        try{
            pst = con.prepareStatement("delete from issue_book where issue_id = ?");
            pst.setString(1, issueIDTextField.getText());
            pst.execute();
            
            rs.close();
            pst.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    public void ReturnUpdate(){
        try{
            Increment in = new Increment();
            int id = in.ReturnBookIncrement();
            pst = con.prepareStatement("insert into return_book values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setInt(1, id);
            pst.setString(2, studentNameTextField.getText());
            pst.setString(3, studentIDTextField.getText());
            pst.setString(4, studentCourseTextField.getText());
            pst.setString(5, studentYearTextField.getText());
            pst.setString(6, studentSemesterTextField.getText());
            pst.setString(7, bookNameTextField.getText());
            pst.setString(8, bookIDTextField.getText());
            pst.setString(9, bookEditionTextField.getText());
            pst.setString(10, bookPublisherTextField.getText());
            pst.setString(11, bookPriceTextField.getText());
            pst.setString(12, dateOfIssueTextField.getText());
            pst.setString(13, (String)dateChooserCombo1.getText());
            int result = pst.executeUpdate();
            if(result ==1){
                JOptionPane.showMessageDialog(null, "Book Returned");
            }
            else{
                JOptionPane.showMessageDialog(null, "Something went wrong...");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                rs.close();
                pst.close();
                con.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnBookPanel = new javax.swing.JPanel();
        studentCourseLabel = new javax.swing.JLabel();
        studentYearTextField = new javax.swing.JTextField();
        studentCourseTextField = new javax.swing.JTextField();
        bookPublisherLabel = new javax.swing.JLabel();
        bookIDTextField = new javax.swing.JTextField();
        dateOfIssueLabel = new javax.swing.JLabel();
        studentIDLabel = new javax.swing.JLabel();
        studentYearLabel = new javax.swing.JLabel();
        studentSemesterLabel = new javax.swing.JLabel();
        bookPriceLabel = new javax.swing.JLabel();
        bookEditionTextField = new javax.swing.JTextField();
        studentIDTextField = new javax.swing.JTextField();
        studentSemesterTextField = new javax.swing.JTextField();
        bookPriceTextField = new javax.swing.JTextField();
        bookPublisherTextField = new javax.swing.JTextField();
        studentNameLabel = new javax.swing.JLabel();
        bookNameTextField = new javax.swing.JTextField();
        bookIDLabel = new javax.swing.JLabel();
        dateOfIssueTextField = new javax.swing.JTextField();
        bookEditionLabel = new javax.swing.JLabel();
        bookNameLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        studentNameTextField = new javax.swing.JTextField();
        issueIDLabel = new javax.swing.JLabel();
        issueIDTextField = new javax.swing.JTextField();
        returnBookLabel = new javax.swing.JLabel();
        returnBookImageLabel = new javax.swing.JLabel();
        dateOfReturnLabel = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        returnBookButton = new javax.swing.JButton();
        backToHomeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Return Book");

        returnBookPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        studentCourseLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        studentCourseLabel.setText("Course");

        studentYearTextField.setEditable(false);
        studentYearTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        studentCourseTextField.setEditable(false);
        studentCourseTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        bookPublisherLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookPublisherLabel.setText("Publisher");

        bookIDTextField.setEditable(false);
        bookIDTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        dateOfIssueLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dateOfIssueLabel.setText("Date of Issue");

        studentIDLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        studentIDLabel.setText("Student ID");

        studentYearLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        studentYearLabel.setText("Year ");

        studentSemesterLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        studentSemesterLabel.setText("Semester");

        bookPriceLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookPriceLabel.setText("Price");

        bookEditionTextField.setEditable(false);
        bookEditionTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        studentIDTextField.setEditable(false);
        studentIDTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        studentSemesterTextField.setEditable(false);
        studentSemesterTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        bookPriceTextField.setEditable(false);
        bookPriceTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        bookPublisherTextField.setEditable(false);
        bookPublisherTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        studentNameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        studentNameLabel.setText("Student Name");

        bookNameTextField.setEditable(false);
        bookNameTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        bookIDLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookIDLabel.setText("Book ID");

        dateOfIssueTextField.setEditable(false);
        dateOfIssueTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        bookEditionLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookEditionLabel.setText("Edition");

        bookNameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bookNameLabel.setText("Book Name");

        searchButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        studentNameTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        issueIDLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        issueIDLabel.setText("Issue ID");

        issueIDTextField.setEditable(false);
        issueIDTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        javax.swing.GroupLayout returnBookPanelLayout = new javax.swing.GroupLayout(returnBookPanel);
        returnBookPanel.setLayout(returnBookPanelLayout);
        returnBookPanelLayout.setHorizontalGroup(
            returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnBookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentSemesterLabel)
                    .addComponent(studentYearLabel)
                    .addComponent(studentCourseLabel)
                    .addComponent(studentIDLabel)
                    .addComponent(studentNameLabel)
                    .addComponent(issueIDLabel))
                .addGap(43, 43, 43)
                .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentCourseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(returnBookPanelLayout.createSequentialGroup()
                        .addComponent(studentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton))
                    .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(issueIDTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(studentSemesterTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addGap(69, 69, 69)
                .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookEditionLabel)
                    .addComponent(bookPublisherLabel)
                    .addComponent(bookPriceLabel)
                    .addComponent(dateOfIssueLabel)
                    .addComponent(bookIDLabel)
                    .addComponent(bookNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateOfIssueTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookPriceTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookPublisherTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookEditionTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookIDTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        returnBookPanelLayout.setVerticalGroup(
            returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnBookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bookNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchButton)
                        .addComponent(studentNameLabel))
                    .addComponent(bookNameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnBookPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(studentIDLabel))
                    .addGroup(returnBookPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(bookIDLabel))
                    .addGroup(returnBookPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentCourseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookEditionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(bookEditionLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(studentCourseLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentYearLabel)
                    .addComponent(bookPublisherLabel)
                    .addComponent(studentYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookPublisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentSemesterLabel)
                    .addComponent(bookPriceLabel)
                    .addComponent(studentSemesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateOfIssueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateOfIssueLabel)
                        .addComponent(issueIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(issueIDLabel))
                .addContainerGap())
        );

        returnBookLabel.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        returnBookLabel.setForeground(new java.awt.Color(51, 0, 204));
        returnBookLabel.setText("Return Book");

        returnBookImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/issueBook.png"))); // NOI18N

        dateOfReturnLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dateOfReturnLabel.setText("Date of Return");

        dateChooserCombo1.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserCombo1.setCalendarPreferredSize(new java.awt.Dimension(280, 190));
    dateChooserCombo1.setFormat(2);
    dateChooserCombo1.setFieldFont(new java.awt.Font("Calibri", java.awt.Font.PLAIN, 18));

    returnBookButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    returnBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N
    returnBookButton.setText("Return");
    returnBookButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            returnBookButtonActionPerformed(evt);
        }
    });

    backToHomeButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    backToHomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
    backToHomeButton.setText("Back");
    backToHomeButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            backToHomeButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(207, 207, 207)
                    .addComponent(returnBookImageLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(returnBookLabel))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(returnBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(260, 260, 260)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(returnBookButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backToHomeButton))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(dateOfReturnLabel)
                            .addGap(29, 29, 29)
                            .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(returnBookImageLabel))
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(returnBookLabel)))
            .addGap(18, 18, 18)
            .addComponent(returnBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dateOfReturnLabel))
            .addGap(19, 19, 19)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(returnBookButton)
                .addComponent(backToHomeButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHomeButtonActionPerformed
        setVisible(false);
        Home ob = new Home();
        ob.setVisible(true);
    }//GEN-LAST:event_backToHomeButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try{
            pst = con.prepareStatement("select * from issue_book where student_name = ?");
            pst.setString(1, studentNameTextField.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                studentIDTextField.setText(rs.getString(8));
                studentCourseTextField.setText(rs.getString(9));
                studentYearTextField.setText(rs.getString(10));
                studentSemesterTextField.setText(rs.getString(11)); 
                issueIDTextField.setText(rs.getString(1));
                bookNameTextField.setText(rs.getString(2));
                bookIDTextField.setText(rs.getString(3));
                bookEditionTextField.setText(rs.getString(4));
                bookPublisherTextField.setText(rs.getString(5)); 
                bookPriceTextField.setText(rs.getString(6));
                dateOfIssueTextField.setText(rs.getString(12));
                
                rs.close();
                pst.close();
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Student Name");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void returnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookButtonActionPerformed
        Delete();
        ReturnUpdate();
    }//GEN-LAST:event_returnBookButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToHomeButton;
    private javax.swing.JLabel bookEditionLabel;
    private javax.swing.JTextField bookEditionTextField;
    private javax.swing.JLabel bookIDLabel;
    private javax.swing.JTextField bookIDTextField;
    private javax.swing.JLabel bookNameLabel;
    private javax.swing.JTextField bookNameTextField;
    private javax.swing.JLabel bookPriceLabel;
    private javax.swing.JTextField bookPriceTextField;
    private javax.swing.JLabel bookPublisherLabel;
    private javax.swing.JTextField bookPublisherTextField;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JLabel dateOfIssueLabel;
    private javax.swing.JTextField dateOfIssueTextField;
    private javax.swing.JLabel dateOfReturnLabel;
    private javax.swing.JLabel issueIDLabel;
    private javax.swing.JTextField issueIDTextField;
    private javax.swing.JButton returnBookButton;
    private javax.swing.JLabel returnBookImageLabel;
    private javax.swing.JLabel returnBookLabel;
    private javax.swing.JPanel returnBookPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel studentCourseLabel;
    private javax.swing.JTextField studentCourseTextField;
    private javax.swing.JLabel studentIDLabel;
    private javax.swing.JTextField studentIDTextField;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JTextField studentNameTextField;
    private javax.swing.JLabel studentSemesterLabel;
    private javax.swing.JTextField studentSemesterTextField;
    private javax.swing.JLabel studentYearLabel;
    private javax.swing.JTextField studentYearTextField;
    // End of variables declaration//GEN-END:variables
}
