package librarymanagementsystem;

import java.sql.*;
import javax.swing.JOptionPane;

public class SignUp extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public SignUp() {
        initComponents();
        con = JavaConnect.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newLibrarianAccountPanel = new javax.swing.JPanel();
        backToLibrarianLoginButton = new javax.swing.JButton();
        librarianUsernameLabel = new javax.swing.JLabel();
        answerOfSecurityQuestionTextField = new javax.swing.JTextField();
        securityQuestionComboBox = new javax.swing.JComboBox<>();
        librarianPasswordLabel = new javax.swing.JLabel();
        securityQuestionLabel = new javax.swing.JLabel();
        answerOfSecurityQuestionLabel = new javax.swing.JLabel();
        librarianNameLabel = new javax.swing.JLabel();
        createNewAccountButton = new javax.swing.JButton();
        librarianNameTextField = new javax.swing.JTextField();
        librarianUsernameTextField = new javax.swing.JTextField();
        librarianPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Account");

        newLibrarianAccountPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "New Account", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 24), new java.awt.Color(0, 153, 255))); // NOI18N

        backToLibrarianLoginButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        backToLibrarianLoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        backToLibrarianLoginButton.setText("Back");
        backToLibrarianLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLibrarianLoginButtonActionPerformed(evt);
            }
        });

        librarianUsernameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        librarianUsernameLabel.setText("Username");

        answerOfSecurityQuestionTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        securityQuestionComboBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        securityQuestionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your mother tongue?", "What is your school name?", "Who is your childhood friend?", "What is your nickname?" }));

        librarianPasswordLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        librarianPasswordLabel.setText("Password");

        securityQuestionLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        securityQuestionLabel.setText("Security Question");

        answerOfSecurityQuestionLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        answerOfSecurityQuestionLabel.setText("Answer");

        librarianNameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        librarianNameLabel.setText("Name");

        createNewAccountButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        createNewAccountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/createAccount.png"))); // NOI18N
        createNewAccountButton.setText("Create");
        createNewAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewAccountButtonActionPerformed(evt);
            }
        });

        librarianNameTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        librarianUsernameTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        librarianPasswordField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        javax.swing.GroupLayout newLibrarianAccountPanelLayout = new javax.swing.GroupLayout(newLibrarianAccountPanel);
        newLibrarianAccountPanel.setLayout(newLibrarianAccountPanelLayout);
        newLibrarianAccountPanelLayout.setHorizontalGroup(
            newLibrarianAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newLibrarianAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newLibrarianAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(librarianNameLabel)
                    .addComponent(librarianUsernameLabel)
                    .addComponent(librarianPasswordLabel)
                    .addComponent(securityQuestionLabel)
                    .addComponent(answerOfSecurityQuestionLabel))
                .addGap(18, 18, 18)
                .addGroup(newLibrarianAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newLibrarianAccountPanelLayout.createSequentialGroup()
                        .addComponent(createNewAccountButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backToLibrarianLoginButton))
                    .addComponent(securityQuestionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answerOfSecurityQuestionTextField)
                    .addComponent(librarianUsernameTextField)
                    .addComponent(librarianNameTextField)
                    .addComponent(librarianPasswordField))
                .addContainerGap())
        );
        newLibrarianAccountPanelLayout.setVerticalGroup(
            newLibrarianAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newLibrarianAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newLibrarianAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(librarianNameLabel)
                    .addComponent(librarianNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newLibrarianAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(librarianUsernameLabel)
                    .addComponent(librarianUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newLibrarianAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(librarianPasswordLabel)
                    .addComponent(librarianPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newLibrarianAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(securityQuestionLabel)
                    .addComponent(securityQuestionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newLibrarianAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerOfSecurityQuestionLabel)
                    .addComponent(answerOfSecurityQuestionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newLibrarianAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNewAccountButton)
                    .addComponent(backToLibrarianLoginButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newLibrarianAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newLibrarianAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToLibrarianLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLibrarianLoginButtonActionPerformed
        setVisible(false);
        LibrarianLogin ob = new LibrarianLogin();
        ob.setVisible(true);
    }//GEN-LAST:event_backToLibrarianLoginButtonActionPerformed

    private void createNewAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewAccountButtonActionPerformed
        try{
            Increment in = new Increment();
            int id = in.signUpIncrement();
            pst = con.prepareStatement("insert into librarian values(?,?,?,?,?,?)");  
            pst.setInt(1, id);
            pst.setString(2, librarianNameTextField.getText());
            pst.setString(3, librarianUsernameTextField.getText());
            pst.setString(4, librarianPasswordField.getText());
            pst.setString(5, (String) securityQuestionComboBox.getSelectedItem());
            pst.setString(6, answerOfSecurityQuestionTextField.getText());
            int result = pst.executeUpdate();
            if(result==1){
                JOptionPane.showMessageDialog(null,"New Account Created");     
            }
            else{
                 JOptionPane.showMessageDialog(null,"Failed...");
            }
            //close Connection
            pst.close();
            con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_createNewAccountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerOfSecurityQuestionLabel;
    private javax.swing.JTextField answerOfSecurityQuestionTextField;
    private javax.swing.JButton backToLibrarianLoginButton;
    private javax.swing.JButton createNewAccountButton;
    private javax.swing.JLabel librarianNameLabel;
    private javax.swing.JTextField librarianNameTextField;
    private javax.swing.JPasswordField librarianPasswordField;
    private javax.swing.JLabel librarianPasswordLabel;
    private javax.swing.JLabel librarianUsernameLabel;
    private javax.swing.JTextField librarianUsernameTextField;
    private javax.swing.JPanel newLibrarianAccountPanel;
    private javax.swing.JComboBox<String> securityQuestionComboBox;
    private javax.swing.JLabel securityQuestionLabel;
    // End of variables declaration//GEN-END:variables
}
