package librarymanagementsystem;

import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class Statistics extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst;  
    ResultSet rs;
    
    public Statistics() {
        initComponents();
        con = JavaConnect.ConnecrDb();
        jTable1();
        jTable2();
    }
    
    public void jTable1(){
        try{
            pst = con.prepareStatement("select * from issue_book");
            rs = pst.executeQuery();
            issueDetailsTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void jTable2(){
        try{
            pst = con.prepareStatement("select * from return_book");
            rs = pst.executeQuery();
            returnDetailsTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        issueAndReturnDetailsPanel = new javax.swing.JPanel();
        returnDetailsPanel = new javax.swing.JPanel();
        returnDetailsScrollPane = new javax.swing.JScrollPane();
        returnDetailsTable = new javax.swing.JTable();
        issueDetailsPanel = new javax.swing.JPanel();
        issueDetailsScrollPane = new javax.swing.JScrollPane();
        issueDetailsTable = new javax.swing.JTable();
        backToHomeButton = new javax.swing.JButton();
        issueDetailsLabel = new javax.swing.JLabel();
        returnDetailsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Issue and Return Statistics");

        returnDetailsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        returnDetailsTable.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        returnDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        returnDetailsScrollPane.setViewportView(returnDetailsTable);

        javax.swing.GroupLayout returnDetailsPanelLayout = new javax.swing.GroupLayout(returnDetailsPanel);
        returnDetailsPanel.setLayout(returnDetailsPanelLayout);
        returnDetailsPanelLayout.setHorizontalGroup(
            returnDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnDetailsScrollPane)
                .addContainerGap())
        );
        returnDetailsPanelLayout.setVerticalGroup(
            returnDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnDetailsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        issueDetailsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        issueDetailsTable.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        issueDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        issueDetailsScrollPane.setViewportView(issueDetailsTable);

        javax.swing.GroupLayout issueDetailsPanelLayout = new javax.swing.GroupLayout(issueDetailsPanel);
        issueDetailsPanel.setLayout(issueDetailsPanelLayout);
        issueDetailsPanelLayout.setHorizontalGroup(
            issueDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issueDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(issueDetailsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
                .addContainerGap())
        );
        issueDetailsPanelLayout.setVerticalGroup(
            issueDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issueDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(issueDetailsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backToHomeButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        backToHomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        backToHomeButton.setText("Back");
        backToHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToHomeButtonActionPerformed(evt);
            }
        });

        issueDetailsLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        issueDetailsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/issue.png"))); // NOI18N
        issueDetailsLabel.setText("Issue Details");

        returnDetailsLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        returnDetailsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N
        returnDetailsLabel.setText("Return Details");

        javax.swing.GroupLayout issueAndReturnDetailsPanelLayout = new javax.swing.GroupLayout(issueAndReturnDetailsPanel);
        issueAndReturnDetailsPanel.setLayout(issueAndReturnDetailsPanelLayout);
        issueAndReturnDetailsPanelLayout.setHorizontalGroup(
            issueAndReturnDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issueAndReturnDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(issueAndReturnDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(issueAndReturnDetailsPanelLayout.createSequentialGroup()
                        .addGroup(issueAndReturnDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backToHomeButton)
                            .addGroup(issueAndReturnDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(issueDetailsLabel)
                                .addComponent(returnDetailsLabel)
                                .addComponent(issueDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        issueAndReturnDetailsPanelLayout.setVerticalGroup(
            issueAndReturnDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issueAndReturnDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(issueDetailsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(issueDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnDetailsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backToHomeButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(issueAndReturnDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(issueAndReturnDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHomeButtonActionPerformed
        setVisible(false);
        Home ob = new Home();
        ob.setVisible(true);
    }//GEN-LAST:event_backToHomeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToHomeButton;
    private javax.swing.JPanel issueAndReturnDetailsPanel;
    private javax.swing.JLabel issueDetailsLabel;
    private javax.swing.JPanel issueDetailsPanel;
    private javax.swing.JScrollPane issueDetailsScrollPane;
    private javax.swing.JTable issueDetailsTable;
    private javax.swing.JLabel returnDetailsLabel;
    private javax.swing.JPanel returnDetailsPanel;
    private javax.swing.JScrollPane returnDetailsScrollPane;
    private javax.swing.JTable returnDetailsTable;
    // End of variables declaration//GEN-END:variables
}
